version: '3'
services:
  app:
    platform: linux/arm/v6
    build: .
    ports:
     - "80:80"
    volumes:
     - /var/log/erv/:/var/log/erv/
    devices:
     - "/dev/gpiomem"
     - "/dev/i2c-1"
    restart: "unless-stopped"
