version: '3'
services:
  app:
    platform: linux/arm/v5
    command: uwsgi --ini /etc/wsgi/wsgi.ini
    image: boxenofdonuts/erv-api:latest
    expose:
      - 5000
    volumes:
     - /var/log/erv/:/var/log/erv/
     - ./wsgi:/etc/wsgi/
    devices:
     - "/dev/gpiomem"
     - "/dev/i2c-1"
    restart: "unless-stopped"
  nginx:
    image: nginx:stable-alpine
    volumes:
     - ./nginx/:/etc/nginx/conf.d/
    ports:
      - 80:80
    environment:
      - NGINX_ENTRYPOINT_QUIET_LOGS=1
    depends_on:
      - app
    restart: "unless-stopped"
