[project]
name = "app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "flask>=3.1.0",
    "gpiozero>=2.0.1",
    "python-json-logger>=3.2.1",
    "pyuwsgi>=2.0.28.post1",
    "rpi-gpio>=0.7.1",
]
