name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push API
        uses: docker/build-push-action@v6
        with:
          context: ./app
          platforms: linux/arm/v6,linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/erv-api:latest
      -
        name: Build and push Climate
        uses: docker/build-push-action@v6
        with:
          context: ./climate
          platforms: linux/arm/v6,linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/erv-climate:latest